from werkzeug.security import generate_password_hash

data = {
     "Sport":[
        {
            "id": 1,
            "name": "scuba"
        },
        {
            "id": 2,
            "name": "surf"
        },
        {
            "id": 3,
            "name": "kitesurf"
        },
        {
            "id": 4,
            "name": "snorkel"
        }
    ],
    "Account":[
        {
            "id": 1,
            "email": "elianajr1@gmail.com",
            "_password": generate_password_hash("123456", method='pbkdf2:sha256', salt_length=16),
            "username": "elianajr",
            "photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640024461/waterdropper/eliana-sea-dragons_rbm3lv.png",
            "cover_photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640024460/waterdropper/eliana-turtle_e3nrct.png",
            "instagram": "https://www.instagram.com/eliana_jordan/",
            "facebook": "https://www.facebook.com/eliana.jordan.romea",
            "about": "I learn how to dive 7 years ago in Thailand and since the very first moment I got absolute amazed by the underwater world, all colours, fish and feeling the water on top of my head, made me feel like an astronaut who want to meet every single specie. 4 years ago I decided to become instructor to share my passion with everybody!",
            "_is_active": True,
            "_is_waterdropper": True
        },
        {
            "id": 2,
            "email": "puravida@gmail.com",
            "_password": generate_password_hash("123456", method='pbkdf2:sha256', salt_length=16),
            "username": "puravidadiving",
            "photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640024460/waterdropper/pura-vida-logo_tpltcc.png",
	        "cover_photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640024460/waterdropper/pura-vida-cover_km4jhz.png",
            "about": "After 14 years learning and teaching, our motto haven’t changed: passion for the ocean, for you, for teaching y for sharing our little paradise called Koh Tao. We are the first Spanish teaching school and we want to make you feel as part of a big family! We are a SSI center teaching up to instructor.",
            "_is_active": True,
            "_is_waterdropper": False
        },
        {
            "id": 3,
            "email": "folken@gmail.com",
            "_password": generate_password_hash("123456", method='pbkdf2:sha256', salt_length=16),
            "username": "folkencillo",
            "about": "I´m a beautiful Full Stack Developer. Constantly trying to improve and learn. I love drawing and in free time I like to go for free diving. Octopus are one of my favourite marine creatures, My octopus teacher documentary deeply moved me",
            "photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640024630/waterdropper/folken-profile_dxjtge.png",
            "cover_photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640114455/waterdropper/octopus-cover_lqikhi.png",
	        "_is_active": True,
            "_is_waterdropper": True
        },
        {
            "id": 4,
            "email": "indasurf@gmail.com",
            "_password": generate_password_hash("123456", method='pbkdf2:sha256', salt_length=16),
            "username": "indasurf",
            "photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640024460/waterdropper/in_da_surf_bali-logo_s1jmfh.png",
	        "cover_photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640024460/waterdropper/in_da_surf_bali-cover_x322ti.png",
            "about": "We are a family run surf camp in Bali. We do only semi-private surf lessons (max 2 guests with 1 coach) with an individual program according to every guest level and goal what makes our camp suitable for all levels (from beginner to advance surfers).",
            "_is_active": True,
            "_is_waterdropper": False
        },
        {
            "id": 5,
            "email": "ruben@gmail.com",
            "_password": generate_password_hash("123456", method='pbkdf2:sha256', salt_length=16),
            "username": "rubenl",
            "photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640114454/waterdropper/ruben-profile_evmcnp.png",
	        "cover_photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640114455/waterdropper/surf-cover_gyki1r.png",
            "about": "I'm a very calm, hard worker and organized person. After few years working in finance, I met my friend Juan and we started to travel the world surfing at the best turquoise water beaches. Now, I have decided follow my passion and become surf instructor.",
            "_is_active": True,
            "_is_waterdropper": True
        },
        {
            "id": 6,
            "email": "info@c2sky.com",
            "_password": generate_password_hash("123456", method='pbkdf2:sha256', salt_length=16),
            "username": "c2sky",
            "photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640114454/waterdropper/C2Sky-profile_ub4gfi.png",
	        "cover_photo": "https://res.cloudinary.com/dbopipvcs/image/upload/v1640114455/waterdropper/C2Sky-cover_sqosif.png",
            "about": "We are a kitesurfing school. C2Sky has actually a few meanings, firstly as an outdoor activity of kite flying we SEE 2 the Sky. I guess the more obvious is that we jump around from the SEA 2 THE SKY.Then we have the shape of the kites. No doubt we had to add the letter C in our name branding.",
            "_is_active": True,
            "_is_waterdropper": False
        }
    ], 

    "Waterdropper": [
        {
            "id": 1,
            "first_name": "Eliana",
            "last_name": "Jordan",
            "level": "Professional",
            "location": "Madrid",
            "account_id": 1
        },
        {
            "id": 2,
            "first_name": "Juan",
            "last_name": "Guerrero",
            "level": "Intermediate",
            "location": "Malaga",
            "account_id": 3
        },
        {
            "id": 5,
            "first_name": "Ruben",
            "last_name": "Lopez",
            "level": "Advanced",
            "location": "Barcelona",
            "account_id": 3
        }
    ],

    "Center":[
        {
            "id": 1,
            "name": "Pura Vida Diving",
            "address": "9/24, Koh Tao, Surat Thani 84360, Thailand",
            "phone": "111111111",
            "web": "https://www.puravida.com",
            "account_id": 2
        },
        {
            "id": 2,
            "name": "In Da Surf Bali",
            "address": "Jl.Pantai Batu Bolong #32A, Canggu, Kec. Kuta Utara, Kabupaten Badung, Bali 80361, Indonesia",
            "phone": "111111112",
            "web": "https://www.surf.com",
            "account_id": 4
        },
        {
            "id": 2,
            "name": "C2Sky",
            "address": "16 Nguyen Dinh Chieu Street, Mui Ne, Vietnam",
            "phone": "111111113",
            "web": "https://c2skykitecenter.com/",
            "account_id": 6
        },
    ],
    "Hotspot":[ 
        {
            "id": 1,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Diamond´s Rocks – Kilkee, IRLANDA",
            "photo": "https://www.nationalgeographic.com.es/medio/2019/01/30/calzada-de-los-gigantes-irlanda_bfad3b27_1200x630.jpg", 
            "level": "–Novice Level - confirmed",
            "description": "Dive into the heart of the Diamond Rocks, Ireland's magnificent bay on the Atlantic Ocean and go on a wonderful journey. Discover the marine diversity in this place: its varied relief and its exuberant flora. This exceptional site proposes you to admire its rocks sparkling in the rays of the sun made of quartz. It is essential to attend a strange show in the depths: the ballet of the spider crabs. Although this site is protected by a team of professionals, it is accessible to everyone! Much sought after for all its wealth, this gives it a special position among the most beautiful dive sites in Europe. ",
            "latitude": "52.681868982137125",
            "longitude": "-9.661097830308075",
        },

	    {
            "id": 2,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Lofoten Isle, NORUEGA",
            "photo": "https://www.actualidadviajes.com/wp-content/uploads/2018/03/islas-lofoten.jpg", 
            "level": "Advanced level",
            "description": "Norway is known as being a paradise for divers thanks to its many fjords, lakes and rivers provided that it is not afraid of the cold. This country is home to a special fauna and flora: giant seaweed forests, bridges and ruins of all kinds that offer divers a very mysterious experience. Go to the discovery of the Lofoten Islands and let the magic happen! This exceptional dive site with a thousand and one surprises gives you the privilege of observing in winter the most important concentration of orcas feeding on herring. In summer, we invite you to swim in good company with seals. This place is ideal to get away and for the most curious among you. ",
            "latitude": "67.99314858594394",
            "longitude":"13.639706864133027",
        },

	    {
            "id": 3,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Isla de Chios – Mar Egeo, GRECIA",
            "photo": "https://www.grecotour.com/img/cms/grecia/islas-griegas/chios/chios-beach2.jpg", 
            "level": "–Level: novice - experienced",
            "description": "This small island located between Greece and Turkey is the ideal dive site to fully enjoy the Mediterranean. Its variety of fish, its crystal clear waters and its caves will offer you an unforgettable experience in an explosion of colors among red and yellow corals and numerous marine species. Whether you are novice or experienced, this authentic dive site offers you the opportunity to see moray eels and sea turtles before relaxing on one of the magnificent surrounding beaches. This place is especially renowned for its two spectacular sites where fearsome predators and schools of small fish coexist. A classic for fans of great emotions! ",
            "latitude": "38.378470368958354",
            "longitude":"26.126753722547832",
        },
	
	    {
            "id": 4,
            "sport_id": 1,  
            "account_id": 1,
            "name": "La Gabinière – Parque Nacional de Port-Cros, Hyères, FRANCIA",
            "photo": "https://sworld.co.uk/img/img/83/photoAlbum/74685/originals/0.jpg", 
            "level": "–Level: novice - intermediate",
            "description":"La Gabinière in France is an inescapable dive site fortified by lush flora and fauna that offers a beautiful setting combining falls and rocks for the possibility of extensive dives. Sensations assured around an abundance of groupers, barracudas and vegetables like yellow anemones that will amaze you. The quality of the water that you cannot find anywhere else in the world is a great advantage at this dive site that makes it one of the most impressive on the French coasts. ",
            "latitude": "42.988960350591306",
            "longitude":"6.394883310994037",
        },
	
	    {
            "id": 5,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Silfra – Parque Nacional de Thingvellir, ISLANDIA",
            "photo": "https://cdn2.civitatis.com/islandia/thingvellir/galeria/header/silfra-islandia.jpg", 
            "level": "–Level: novice - experienced",
            "description": "The Silfra fissure located in the Thingvellir National Park is an internationally famous dive site, declared a World Heritage Site by UNESCO. Its location makes it the only dive site in the world where you can venture between two tectonic plates: American and Eurasian. Its mineral and drinkable waters come from a glacier and are filtered by volcanic rocks. In short, a water of rare purity and a visibility that does not end! This dive site is made up of 3 parts: Silfra Lake, Silfra Cathedral and Silfra Hall. The one that we can certainly retain is the cathedral with its fissure that does not exceed 100 meters long and 63 meters deep. This place is unique for snorkeling. However, make sure you provide your most beautiful drysuit to keep you comfortable and warm throughout your underwater excursion. In Silfra, change the landscape according to your wishes. They can go from a landscape of foam and vegetation to a tropical part with a mass of light saber that lines the bottom of the fault. Marine life for it is 			mainly made up of live green troll hair and different types of algae. Exploring Silfra is like finding yourself in a parallel world much calmer and more fantastic than normal people.",
            "latitude": "64.25598948495903",
            "longitude":"-21.12959261646408",
        },
	
	    {
            "id": 6,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Blue Hole – Gozo, MALTA",
            "photo": "https://www.descubremalta.com/wp-content/uploads/Blue-Hole-Dwejra-Gozo-scaled.jpg", 
            "level": "- Advanced level",
            "description": "Considered one of the most beautiful dive sites in the world, Blue Hole intrigues tourists who venture there because of its nuanced topography. Created as a large circular hole fifteen meters in diameter, this spot has an infinity of landscapes: caves, falls and arks excavated in the limestone by millions of years of erosion, which makes the trip even more interesting. The more you will go down in depth, the more important will be the marine diversity. You will be able to particularly observe moray eels, small groupers, or rather the Mediterranean parrotfish. However, explorations of the Blue Hole and its underwater ark are reserved for experienced divers. In any case, get ready for a colorful trip! ",
            "latitude": "36.053470848584205",
            "longitude":"14.189040223432258",
        },
	
	    {
            "id": 7,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Secca Della Colombara – Isla Ustica, ITALIA",
            "photo": "https://www.evasionibludiving.com/public/Colombara/prua2.jpg", 
            "level": "- Level: All levels",
            "description": "Endowed with a rich and diversified culture particularly in the luxury and gastronomy sectors, Italy has other advantages as well. Indeed, the country is full of gems like the famous Decca Della Colombara dive site located on Ustica Island. This place accessible to all levels that starts from a depth of 3 meters is ideal for fans of colored seabeds in any case. The lower depths of the Colombara is a true temple of serenity with extensive relief. ",
            "latitude": "38.70367104850455",
            "longitude":"13.16837717816906",
        },

	    {
            "id": 8,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Barracuda Point – isla Sipadan, Mar de Célebes, MALASIA",
            "photo": "https://media.traveler.es/photos/61377a0e32d932c80fcb9de4/16:9/w_1280,c_limit/97540.jpg", 
            "level": "- Level: intermediate - advanced",
            "description": "Barracuda Point is one of the rarest dive sites in the world. Marine life and biodiversity are incredibly rich, with more than 3,000 species of fish and unusual corals of bright color and various shapes abound. In addition, this place is cult for its fantastic show of multicolored fish that swirl around divers. Barracudas and other fish accompany the turtles, a surprising moment that is out of the ordinary. We recommend this dive site for its sublime reliefs and magical discoveries. ",
            "latitude": "4.115102611134124",
            "longitude":"118.62867762666119",
        },
	
	    {
            "id": 9,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Layang Layang – Mar de la China meridional, MALASIA",
            "photo": "https://q-xx.bstatic.com/images/hotel/max1024x768/125/125963951.jpg", 
            "level": "–Level: novice - experienced",
            "description": "Discover Layang Layang along the mythical island of Borneo, an artificial atoll lost in the warm waters of Malaysia made up of 13 coral reefs. This wealthy dive site offers tons of surprises thanks to its rich ecosystem and isolated location. Therefore, it can be considered as a magical place valued by all. The keywords are exploration and relaxation for this islet that only has one hotel. Forget the noise nuisance and pollution, here you are isolated from all contact, in full communion with nature. If you have the opportunity to dive between March and May, you will appreciate the clarity of the water to be able to observe some hammerhead sharks that circulate alone or in groups. This attraction is what made Layang Layang famous. ",
            "latitude": "1.8133874478927179",
            "longitude":"103.4783261818411",
        },
	
	    {
            "id": 10,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Crystal Bay – Bali, Mar de Java, INDONESIA",
            "photo": "https://q-xx.bstatic.com/images/hotel/max1024x768/125/125963951.jpg", 
            "level": "–Level: Experienced",
            "description": "Fans of great sensations and experienced divers, this dive site is made for you! Crystal Bay is a Bali dive essential that can leave you speechless. Enter an explosion of colors and nuances observing soft corals but also fish that are out of order and that mix in the middle of the caves and sandy soils. For the most fortunate among you, between July and November you will have the opportunity to attend the rise of the star fish of this site, the Mola-Mola, an impressive marine creature with a wingspan between 2 and 3 meters, which came in order to be dewormed by other species of fish. Unfortunately, if you have missed that opportunity, don't despair. They could still admire the famous and interesting cave of the bats. A program full of emotions awaits you. ",
            "latitude": "-8.715282582410516",
            "longitude":"115.45903068269708",
        },

	    {
            "id": 11,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Lembeh Strait – isla Sulawesi, INDONESIA",
            "photo": "https://www.lembehresort.com/wp-content/uploads/East-Lembeh-768x303.jpg", 
            "level": "–Level: Experienced",
            "description":"Legend has it that the murkier the water is, the more strange creatures abound. Lembeh Strait, a dive site located in the northeast of Sulawesi Island, confirms this belief. With poor visibility, it offers an ideal environment for all photographers and divers who love small underwater creatures. This site allows in particular to observe the resplendent cuttlefish, the rare mimic octopus or rather the ugly striated frogfish. Novices are advised not to venture into this unsuitable dive site, but a must for advanced divers. However, this place has a wonderful biodiversity that will seduce you. ",
            "latitude": "1.4536608216884959",
            "longitude":"125.22501164980552",
        },

	    {
            "id": 12,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Castle Rock – Komodo, INDONESIA",
            "photo": "https://www.buscabuceo.com/data/u/62/inmersion/642/gal/castle-rock-komodo-indonesia-indonesia-w-2.jpg", 
            "level": "–Level: novice and more",
            "description":"Embark on a fantastic journey at Castle Rock, one of the most popular dive sites in Thailand's Komodo National Park. This place with rich relief: drift, rocky plateau, coral reef ... offers an optimal environment for lovers of diving. Enjoy fully the clean waters of Castle Rock to start diving, accessible to all levels. Small fish abound in the mist of the seabed, attracting fearsome predators such as dolphins and chunk sharks, giving this exploration an astonishing aspect. Flora also finds its place in the strong presence of fauna. Between nudibranchs, soft corals and hard corals and sponges, your eyes will light up! Equip yourself with your most beautiful camera with a close-up lens and get adventurous! ",
            "latitude": "-8.574949038619442",
            "longitude":"119.4492696180999",
        },

	    {
            "id": 13,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Cape Kri – Raja Ampat, INDONESIA",
            "photo": "https://mochilerosentailandia.com/wp-content/uploads/2019/02/que-hacer-en-puerto-galera.jpg", 
            "level": "–Level: confirmed - experienced",
            "description": "The Raja Ampat archipelago, which means the four kings, is made up of more than 1500 islands, of which the main ones are: Misool, Salawati, Batanta and Waigeo. It is said that the Cape Kri abounds with marine species of all kinds… to say the least! Indeed, it is in these waters that the world record for the number of different species (no less than 374) in a single dive was achieved. With more than 1000 species of fish, more than 500 species of corals and more than 700 species of mollusks, the archipelago is one of the 5 best destinations in the world for diving. Ecosystems and biodiversity are preserved from mass tourism and intensive fishing, not yet highly developed, so the dives are a real pleasure. They will be isolated from the world in an environment that mixes lakes, mangrove forests and deserted beaches to take the time to observe everything that walks at the bottom of the water, a beautiful painting speckled with striking colors .. ",
            "latitude": "-0.5610169965147398",
            "longitude":"130.67678368352117",
        },

	    {
            "id": 14,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Puerto Galera – isla de Mindoro, FILIPINAS",
            "photo": "https://mochilerosentailandia.com/wp-content/uploads/2019/02/que-hacer-en-puerto-galera.jpg", 
            "level": "–Level: Novice - Experienced",
            "description":"Also known as “La Perla de Mindoro”, the Puerto Galera dive site proposes you to immerse yourself in a relaxing and tropical dive among coconut trees and white sand beaches. This biosphere reserve is considered one of the most beautiful bays in the world. Here you will find the most flourishing coral gardens in the Philippines, where an extraordinary fauna lives in water around 30 ° C during the warm seasons. This dive site is also a sacred place for underwater photography for all its animal, plant and mineral wealth. It is possible to go crazy! ",
            "latitude": "13.48887513948786",
            "longitude":"120.95216812747033",
        },

	    {
            "id": 15,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Apo Reef – Mar de Sulu et Mar de China, FILIPINAS",
            "photo": "https://cdni.rt.com/actualidad/public_images/2021.04/article/r/700/90/jpeg/6066f8ae59bf5b49896e3ebc.jpg", 
            "level": "–Level: novice - experienced",
            "description":"Apo Reef is the largest coral reef in the Philippines. It is a marine reserve with an area of ​​15,800 hectares that extends to more than 40 km². This very favorable site for various dives is supervised by local park rangers who limit disturbances from overfishing. Apo Reef is made up of three islets. In this dive site you will find: Cayos del Bajo submerged by the tides, Apo Minor which is an island mainly covered with limestone where the vegetation is very poor and finally Apo Island which on the contrary is rich in vegetation and which forms a mini mangrove This place owes its reputation to its abundance of corals and marine species. In total, more than 350 species are listed. This dive site has many advantages, including its nightly expeditions in exceptionally clear waters. In short, a paradise for any diver who dreams of getting away! ",
            "latitude": "8.814569595893012",
            "longitude":"120.85770690522057",
        },

	    {
            "id": 16,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Roca de Richelieu – Mar de Andaman, Oeste de Phuket, TAILANDIA",
            "photo": "https://imagenes.20minutos.es/files/article_amp/uploads/imagenes/2020/01/31/phang-nga-bay-tailandia.jpeg", 
            "level": "–Level: advanced - experienced",
            "description": "Richelieu Rock, more commonly known as Richelieu Rock, is THE SPOT of diving in Thailand. This large rock almost completely submerged depending on the mood of the tide (low or high) offers an idyllic setting for any diver who wishes to venture there. The topography of this dive site is very popular and attracts a high density and diversity of tropical fish. This place allows, with a bit of luck, to see whale sharks between the months of February and May. Thanks to its environment, macro photography lovers will also find their happiness among amazing microorganisms and multi-colored corals in abundance. This dive site is the best of the best among the places in Thailand for all the enthusiasts. ",
            "latitude": "7.873953731680778",
            "longitude":"98.40269724631537",
        },

	    {
            "id": 17,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Hin Daeng et Hin Muang – Koh-Lanta, Mar de Andaman, TAILANDIA",
            "photo": "https://consejerosviajeros.com/wp-content/uploads/2017/04/3.-Diving-en-Hin-Daeng.jpg", 
            "level": "–Level: advanced - experienced",
            "description": "These two twin dive sites are among the best in Thailand. Hin Daeng (the Red Rock) and Hin Muang (the Purple Rock) can boast of their success with divers around the world. These places of turbulent waters by plankton are full of surprises and mysteries of all kinds: stingrays, whale sharks and more in depth in the sand it is not uncommon to find leopard sharks, reef sharks as well as rays with black spots. These dive sites are also major refuges for macro creatures like ghost marlin, harlequin shrimp, and long-beaked hawkfish. In short, a shock duo for the most curious of you! ",
            "latitude": "8.053205142739793",
            "longitude":"98.90458921179118",
        },

	    {
            "id": 18,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Islas Wolf y Darwin – Archipiélago des Galapagos, ECUADOR",
            "photo": "https://1.bp.blogspot.com/-2QSutSInxpY/Wmn8am8h6RI/AAAAAAAABNg/BYSzRWfF75MdrnmOWSYmCnNH9ESIqAEyQCLcBGAs/s1600/Isla%2BDarwin.PNG", 
            "level": "–Level: advanced - experienced",
            "description": "Wolf and Darwin, two mythical names in underwater diving for all specialists around the world. These two sites that are only accessible by dive cruises are undoubtedly the most famous in the Galapagos archipelago. Protected islands and declared a UNESCO World Heritage Site in 1978, the Galapagos Islands can boast of its unmatched biodiversity in the world with almost 3,000 identified marine species. It is also a well of science and history that allowed Charles Darwin to theorize his idea of ​​the evolution of species by natural selection in 1835. Wolf and Darwin put on an extraordinary show orchestrated by impressive marine life and an abundance of pelagics. Among whale sharks, hammer and Galapagos sharks, eagle rays and dolphins, we don't know where to pay attention. A subtle mix of rocks, dizzying cliffs and caves make these dive sites the most unusual and fascinating in the world. Certainly your most unforgettable diving trip! ",
            "latitude": "1.384603839556781",
            "longitude":"-91.81584485280567",
        },
	
	    {
            "id": 19,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Bajo Alcyone et Dirty Rock – Isla Coco, COSTA RICA",
            "photo": "https://dsvsbigncb06y.cloudfront.net/site/diving/costa-rica/liveaboard-costa-rica-xxl.jpg", 
            "level": "–Level: experienced",
            "description":"In front of Costa Rica is proudly the island of Cocos, around which you can see a score of the most incredible dive sites among themselves. Its protection and isolation earned it a privileged UNESCO World Heritage site since the 1990s and it is also a little paradise for the species that live there. Its natural architecture is impressive, covered with forests with huge waterfalls that reach the sea. Two essential sites on Cocos Island only accessible by diving trip, Bajo Alcyone and Dirty Rock unavoidable attraction that you should not miss during your diving trip that are home to a large number of marine species and especially sharks of all kinds. The reliefs and the preserved environment in Bajo Alcyone and Dirty Rock are of pure beauty mixing submerged mountains and crevasses where the biomass of small species is the most developed in the world. In short, the Grail for divers of any horizon that makes it one of the most appreciated dive sites in the world. ",
            "latitude": "5.529875521028151",
            "longitude":"-87.056662094107",
        },
	
	    {
            "id": 20,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Cenote Dos Ojos – Playa del Carmen, MÉXICO",
            "photo": "https://media.tacdn.com/media/attractions-splice-spp-674x446/06/7b/1e/eb.jpg", 
            "level": "–Level: novice - experienced",
            "description": "Los Ojos, owes its name to the two cenotes of a very close circular shape. A cenote is an underground formation that can reach hundreds of kilometers underground. Fresh water and salt water come together for your happiness, whether you are a beginner who wants to discover snorkeling or dive regularly. The two main dive sites that make up this cenote are the Barbarie line and the Bat cave. Los Ojos is one of the 10 longest underwater cave systems in the world. Enter a magical environment and stop for a moment to contemplate the splendid geological formations of the sea floors: caves, columns and vaults caressed by the gentle rays of the sun that pass through the crystal clear waters. It could even be that a group of bats greets you perched on the walls. A show out of the ordinary and of which we never tire! ",
            "latitude": "20.324903249102537",
            "longitude":"-87.39044898392622",
        },
	
	    {
            "id": 21,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Socorro – Archipiélago de Revillagigedo, MÉXICO",
            "photo": "https://cdn-3.expansion.mx/dims4/default/2c856f2/2147483647/strip/true/crop/1200x630+0+101/resize/1200x630!/format/jpg/quality/80/?url=https%3A%2F%2Fcherry-brightspot.s3.amazonaws.com%2F50%2Fcd%2F9230854f4a9ab07c31457131f265%2Farchi-efe.jpg", 
            "level": "–Level: Experienced",
            "description": "Considered a World Heritage Site by UNESCO in 2016, Socorro is the largest of the four volcanic islands of the Revillagigedo archipelago with San Benedicto, Roca Partida and Clarion. Lost in the middle of the Pacific Ocean, the island of Socorro is also known as the Galapagos of Mexico. This incredible vegetation covered dive site is full of lava flows where the current is strong and in fact reserved for experienced divers. You will be able to catch a glimpse of many pelagic species, any type of shark, as well as specially colored fish. On the other hand, they will not find flora in the depths of its waters. This haven of peace without human nuisance or pollution is a true underwater immersion experience closer to nature that you will never forget! ",
            "latitude": "18.805477406739232",
            "longitude":"-110.97567539969295",
        },
	
	    {
            "id": 22,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Isla Malpelo, COLOMBIA",
            "photo": "https://noticias.masverdedigital.com/wp-content/uploads/2020/06/colombiaislademalpelob.jpg", 
            "level": "–Level: confirmed - experienced",
            "description": "The island of Malpelo, which can only be accessed by diving cruise, is a veritable isolated underwater temple where rich fauna and flora abound, especially in terms of endemic species. The pinnacles and rocks that surround the island are sacred dive sites in Colombia that are full of pelagic and corals in excellent health due to the high solar intensity and the very pure water without pollution. The humid tropical climate, currents and the plurality of reliefs favor reproduction on the island, making it a beautiful and dynamic dive site. ",
            "latitude": "4.007181264877221",
            "longitude":"-81.59391154233255",
        },
	
	    {
            "id": 23,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Scotts Head – Reserva marina natural, Sur de Roseau, DOMINICA",
            "photo": "https://www.travelsauro.com/wp-content/uploads/2016/01/scotts-head-dominica-1.jpg", 
            "level": "–Level: novice - experienced",
            "description": "The Soufrière Scotts Head Marine Reserve, managed since 1998 by a local collegiate authority made up of coast guards, municipal councilors, associations and the local fisheries committee, is full of rare treasures, not material, but which nature has sculpted over time. The topography is splendid, mainly composed of caves, pinnacles and lava flows. Flora and fauna flock to the site, which makes it very alive. This dive site is ideal for underwater photography with the contrasting plays of light in the caves offering divers great opportunities to take clichés. It is especially this last feature that will matter to us during a Scotts Head dive trip! ",
            "latitude": "15.213901133778927",
            "longitude":"-61.371860571784595",
        },

	    {
            "id": 24,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Great Blue Hole – Arrecife Lighthouse, BELIZE",
            "photo": "https://www.visitcentroamerica.com/wp-content/uploads/2017/11/ver-centroamerica-belice-blue-hole-naturaleza-01.jpg", 
            "level": "–Level: novice - confirmed",
            "description": "Made famous by Jacques Cousteau in the 1970s and a UNESCO World Heritage Site since 1996, the Great Blue Hole is a famous dive site located about 65 km from Belize, which is part of the Lighthouse Reef. The latter is an atoll formation that offers endless opportunities for diving, be it falls, drifts, or coral gardens. The Great Blue Hole is a huge hole almost 300 meters in diameter by almost 125 meters deep. This dive site with its location, its rich and varied topography and the excellent visibility of its waters is home to a diverse and abundant fauna and flora. Immerse yourself in the darkness of the abysses and find the blacktip reef sharks admiring the stalactites along with the shoals. All these factors make it a fantastic dive destination! ",
            "latitude": "17.31150840529181",
            "longitude":"-87.55592074502954",
        },

	    {
            "id": 25,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Précontinent II Sha’ab Rumi Sud – Mar Rojo, SUDAN",
            "photo": "https://www.buscabuceo.com/data/u/62/inmersion/108/gal/precontinent-ii-arrecife-de-shaab-rumi-m-3.jpg", 
            "level": "–Level: All levels",
            "description": "The Tiger Beach dive site located in Grand Bahamas is, as the name suggests, the refuge for tiger sharks… but not only that! They will also have the opportunity to find other types of sharks: hammerheads, chunks or even lemons. This place is aimed at divers in search of emotions and great sensations, but it remains open at all levels because there is no current and the funds are shallow. Conditions are ideal for diving, so they don't waste a minute getting into the water. ",
            "latitude": "20.328795766009538",
            "longitude":"38.54814622786757",
        },

	    {
            "id": 26,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Isla Mnemba – Archipiélago de Zanzibar, TANZANIA",
            "photo": "https://album.mediaset.es/eimg/10000/2021/06/25/clipping_hSBOxP_fa10.jpg", 
            "level": "–Level: novice - experienced",
            "description": "The unpretentious Mnemba Island in Zanzibar is a paradise for its white sand beaches and a key place for diving and snorkeling, whose environment is safeguarded and protected by the government and local communities. Hold your breath as you may never want to leave the crystal clear waters of this multi-colored dive site full of fish and coral. Dive outings are accessible to all and offer a wide range of opportunities for diving or snorkelling in constantly changing seascapes. An obligation to fully enjoy. ",
	        "latitude": "-5.820361891561495",
            "longitude":"39.38350598690334",
        },

	    {
            "id": 27,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Aliwal Shoal – Umkomaas, SUDAFRICA",
            "photo": "https://www.south-coast-info.co.za/info/towns/1677/images/bottom_images/10.jpg", 
            "level": "–Level: advanced - experienced",
            "description": "The place of the cow whales, called Umkomaas in Zulu is a city in South Africa with numerous more incredible dive sites of each other. Especially the Aliwal Shoal reef, an essential place for a diving trip in warm waters full of fish and vegetation, known worldwide for its sharks. In fact, you will have the opportunity to dive with rare species such as the bull shark that breeds in these waters, but also the tiger shark, the striped shark, the hammerhead shark and the Zambezi shark. They will also be able to see rays, turtles, groupers, and sometimes whale sharks. For a dive cruise, you will have the honor of being accompanied by very friendly dolphins. Your company adds a lot of charm to this dive site. It makes us want to jump into the water! ",
            "latitude": "-30.246209416039616",
            "longitude":"30.817595087431673",
        },

	    {
            "id": 28,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Protea Banks, SUDAFRICA",
            "photo": "https://taucher.net/media/images/w850/b0/dc/b8/b0dcb8222d901073ae17a0c40dc00f60.JPG", 
            "level": "–Level: Experienced",
            "description": "Protea Banks in South Africa is without a doubt the best dive site in the world to see sharks in their habitat. The presence of a large number of tuna favors their arrival to the great joy of divers in search of great sensations and emotions. This place includes 3 main areas: Northern Pinnacle, Southern Pinnacle and Playground that have impressive marine architecture between caves, rocks and canyons. This is the favorite playground of many different species of sharks. A great white shark was once seen at the Playground! Therefore, it is normal that this dive site is reserved for experienced divers.",
            "latitude": "-30.832595557367853",
            "longitude":"30.48281828771171",
        },
	
	    {
            "id": 29,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Sardine Run, SUDAFRICA",
            "photo": "https://www.tripsavvy.com/thmb/PicnORo_HMiDOR01h7crU27WrA0=/2119x1417/filters:fill%28auto,1%29/sharkandbaitball-565ba1933df78c6ddf5c2e02.jpg", 
            "level": "–Level: confirmed - experienced",
            "description": "A fabulous adventure awaits you. Go for the Sardine Run, an amazing spectacle in which millions of sardines climb along the coasts of South Africa to Mozambique in the months of June and July. This experience is unique and offers you the opportunity to admire an impressive number of pelagics, marine species and birds that feed on millions of seedlings and sardines. They will be able to see predators of all kinds such as dolphins, sharks, whales, sea lions, seagulls and even fishermen! When diving or staying on the boat, it is an experience for all divers or the curious worthy of the name.",
            "latitude": "-30.10598318707761",
            "longitude":"30.796306212438754",
        },
	
	    {
            "id": 30,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Elphinstone Reef – Mar Rojo, EGIPTO",
            "photo": "http://www.joveneslowcost.com/contenido/uploads/2016/10/j-mar-rojo-2.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Considered by many divers to be the most famous reef in Egypt, or even the Red Sea, Elphinstone Reef, named for George Elphinstone, a British admiral in Egypt during the Napoleonic wars, stretches for almost 300 meters and rises to the surface of the water with two trays on each side that appear to fall down steps like stairs. The brightness emanating from the sun is essential in this site that is full of animal and plant life to enjoy the incredible colors of the backgrounds. Sponges, soft corals, gorgonians, oceanic sharks and hammerhead sharks are the main attractions for divers and make this site exceptional and very exciting to explore!",
            "latitude": "25.30980315224955",
            "longitude":"34.86053105748025",
        },
	
	    {
            "id": 31,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Blue Hole – Dahab, Mar Rojo, EGIPTO",
            "photo": "https://upload.wikimedia.org/wikipedia/commons/b/bf/BlueHole_Rohscan_bearb_150d.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "The Blue Hole or blue hole in Spanish is a famous dive site in Egypt more than 100 meters deep, located about 20 minutes from Dahab and accessible from the beach. Although fascinating and mysterious, this place is still infamous for its dangerousness, so beginners are advised not to venture there. The dives are quite reserved for tek divers. Generally, the dive starts at The Bells, a hundred meters away. Further down you will find the Arch very frequented by groups of caranidae, sharks, turtles but also stingrays. It is impossible to explore this part without professional equipment and solid experience. For beginners, we recommend trying snorkeling, with multiple opportunities for surprising and colorful encounters such as clownfish in their anemones, butterflyfish, and parrotfish. In short, this dive site is one of the best in the world for its unexpected finds, but also the most risky.",
            "latitude": "28.572521982077397",
            "longitude":"34.537353613345594",
        },
	
	    {
            "id": 32,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Shark and Yolanda Reef – Parque Nacional de Ras Mohammed, Mar Rojo, EGIPTO",
            "photo": "https://www.cairotoptours.com/uploads/pages/a89c106af5d3fd005e94c7e249bcd226.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "At the southern tip of the Sinai Peninsula, two reefs emerge from the abyss: the shark and the Yolanda Reef, each possessing their own currents and endemic species. At Shark Reef, a drop more than 800 meters deep is completely covered in soft corals and schools of snappers abound. They are also found on the sandy bottoms of giant moray eels, groupers, and blue-spotted stingrays while at Yolanda Reef, coral potatoes are ubiquitous with their altimeians and gorgonians. You can see the remains of the wrecks of the Yolanda that sank in 1980, which gave the reef its name. On this site, it is common to photograph a Javanese moray head emerging from a toilet bowl. For all these reasons, the Shark and Yolanda Reef dive site was ranked in the top 10 most beautiful sites to explore during a dive trip.",
            "latitude": "27.742118229731854",
            "longitude":"34.23496741703863",
        },
	
	    {
            "id": 33,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Islas Hermanos – Mar Rojo, EGIPTO",
            "photo": "https://www.cairotoptours.com/uploads/pages/a89c106af5d3fd005e94c7e249bcd226.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Between Egypt and Saudi Arabia are the Brothers Islands (Brothers in Spanish), which can only be accessed by diving cruise. Lost in the middle of the Red Sea, the two brothers are classified in the marine park by the Egyptian government and offer a fabulous diversity of fauna and flora that make it one of the most beautiful dive sites in the world. Beneath the waters, a varied topography made up of caves, dizzying falls, and wreckage awaits you for an unusual and confusing expedition. At Big Brother, come visit the lighthouse built in 1883 by the British and then immerse yourself in the backgrounds colored by plant and animal life. In Little Brother, the pelagic fauna dominates. All species of sharks are found in this place for the happiness of divers and the reef is lined with gorgonians and beautiful bushes of black corals. This dive site is undoubtedly one of the most complete in the world!",
            "latitude": "27.941485704185148",
            "longitude":"34.542634352440615",
        },

	    {
            "id": 34,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Manta Reef – Nusa Penida, MOZAMBIQUE",
            "photo": "https://saveourseas.com/wp-content/uploads/2019/09/20190709im03ryandalysaveourseasfoundationcopyright.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "The name of this dive site is not anodyne. Manta Reef is perhaps the best place in Africa to observe giant manta rays and the reproduction of the latter. The stingrays at this site can easily reach 6 meters in wingspan and we can admire them spinning above the divers as they are cleaned by anthias and wrasses. Great entertainment and a beautiful painting to behold! High cliffs hide a great variety of corals and it is not uncommon to find eagle rays, mobulas, not forgetting whale sharks and humpback whales. Your dreams will come true at Manta Reef. You don't have a minute to waste!",
            "latitude": "27.92169401064883",
            "longitude":"34.36804692334349",
        },

	    {
            "id": 35,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Fish Rock Cave – South West Rocks, AUSTRALIA",
            "photo": "https://s1.at.atcdn.net/wp-content/uploads/2012/10/fish-rock-cave-custom-fields.jpg", 
            "level": "–Level: all levels",
            "description": "Fish Rock Cave on the coast of New South Wales, one of the largest underwater caves in the world, but also one of the most famous, attracts divers from all over the world for the serenity of its waters, but it is still full of species rich and varied marinas. Two large dark chimneys emerge from the cavern and immerse you in a magical universe where the female cuttlefish reproduce while the males swim near the silent walking mask turtles. You can admire this spectacle using your flashlight because here the sunlight penetrates very little water. Numerous carpet sharks, bullseyes, bull rays, cowries, sea cucumbers and Spanish dancers also reign at this dive site that we highly recommend.",
            "latitude": "-30.894012229705968",
            "longitude":"153.04027347311728",
        },

	    {
            "id": 36,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Perpendicular Wall – Christmas Island, AUSTRALIA",
            "photo": " https://www.scubadivermag.com/wp-content/uploads/2021/03/Christmas-Island-hard-coral-with-divers-credit-Scott-Portelli_SP13278.jpg", 
            "level": "–Level: experienced",
            "description": "A wall perpendicular to the surface of the water makes the fame and interest of this dive site, which is one of the 40 places found on Christmas Island. The topography is impressive, created by the underwater volcano whose eruptions formed plateaus, reefs and precipices. The funds are also interesting to explore and hide caves where stalactites and stalagmites are spectacular. The site is home to a wide variety of tropical fish, whale sharks, sailfish and humpback parrots that offer a picture among the most nuanced and surprising. A pure pleasure to dive!",
            "latitude": "-34.97225027845969",
            "longitude":"150.8491115590797",
        },

	    {
            "id": 37,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Navy Pier – Parque Marino Ningaloo Reef, Exmouth, AUSTRALIA",
            "photo": "https://www.diveningaloo.com.au/wp-content/uploads/2018/07/navypier1-1024x504.jpg", 
            "level": "–Level: All levels",
            "description": "What diver does not dream of diving in and discovering with his palms more than 250 species of coral, 700 species of fish and 14 species of whales? The Ningaloo Reef Marine Park in the city of Exmouth meets all these criteria and much more, making it a UNESCO World Heritage Site since 2011. The Navy Pier site ranked as one of the top 10 dive sites in the world. It is a protected area that offers incredible biodiversity. You will certainly see carpet sharks and whitetip reef sharks. It is also a very good place to snorkel! Indeed, small marine creatures such as nudibranchs, earthworms, frogfish, scorpionfish and stonefish abound in the great blue for all lovers of underwater photography. A true animal sanctuary under these waters!",
            "latitude": "-21.926760684472768",
            "longitude":"114.15190135367712",
        },

	    {
            "id": 38,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Blue Corner – Palau, MICRONESIA",
            "photo": "https://content.unops.org/photos/News-and-Stories/News/_1200x630_crop_center-center_82_none/Palau_GettyImages-949006476.jpg", 
            "level": "–Level: All levels with current experience",
            "description": "The small island of Micronesia has one of the most extraordinary dive sites in the world for its vast flora and fauna. However, the currents can be extremely strong, which might put off some newbies. Blue Corner is a deep, vertical drop that offers incredible marine diversity, especially pelagic reproduction: gray reef sharks between February and April, corals in May, and groupers in July. Diving conditions are excellent all year round and there will always be something to see!",
            "latitude": "7.343593770566402",
            "longitude":"134.4801204517925",
        },
	
	    {
            "id": 39,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Paso de Tiputa – Atolón de Rangiroa, Polinesia Francesa",
            "photo": "https://unaideaunviaje.com/wp-content/uploads/2020/12/pink-beach-rangiroa-polinesia-francesa-unaideaunviaje-47.jpg", 
            "level": "–Level: novice - experienced",
            "description": "In the Tuamotu archipelago is the Rangiroa Atoll. In this atoll is the Tiputa pass. The latter is one of the most unusual and appreciated dive sites in the world for its impressive marine wealth and its many sites that cater for all levels of diving. It is impossible to speak of Tiputa without naming nearby sites: Angle, the Walk and the Fish-Soldier Reef. The Angle is suitable for experienced divers who wish to observe species such as humpback snapper, climbing bigeye, wrasse or dog's tooth tuna. At the level of the Walk, they are offered an incredible topography with the presence of pelagic species. This dive requires exemplary buoyancy and drifting experience. Finally, the Soldier-Fish Reef has a spectacular fauna and flora. Soldierfish, anemones, clownfish, marbled groupers, whitetip sharks and stingrays can be seen for example. A rare diversity of animals and plants that cannot be found anywhere else.",
            "latitude": "-15.101785451822398",
            "longitude":"-147.65549292539202",
        },
	
	    {
            "id": 40,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Buceo nocturno con mantarrayas – Kailua Kona, HAWAI",
            "photo": "https://images.rove.me/w_1920,q_85/i450ph7xpo3nakxipfwi/big-island-manta-ray-night-dive.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "The night dive with stingrays was voted one of the most popular attractions of your life by the Travel Channel. Come and admire the ballet of the stingrays feeding on seedlings as they swirl around you with the soft lights of the boats that sparkle in the crystal clear waters of Hawaii. A magical and unforgettable night show to observe throughout the year!",
            "latitude": "19.648535514589252",
            "longitude":"-155.99927266268003",
        },
    
        {
            "id": 41,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Pipeline, Oahu, Hawaii",
            "photo": "https://www.coresurfingshop.com/blog/wp-content/uploads/2018/10/wpid-pipeline-.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Here it is -- the granddaddy of all waves. Most surfers will never be good enough to ride here, but everyone dreams of bobbing along its perfect crest. Located on the island where modern surfing was developed, this is one of the heaviest waves in the world, scaling more than six meters over a shallow base of razor-blade table reef. Ride this flawl",
            "latitude": "21.716665474790066",
            "longitude":"-157.9895311342005",
        },

	    {
            "id": 42,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Supertubes, Jeffrey's Bay, South Africa",
            "photo": "https://dl.airtable.com/.attachmentThumbnails/7d20c94597ae414ea2dd004863504fbd/601f8f5b", 
            "level": "–Level: Advanced - experienced",
            "description": "The best right-hand ride in the world, according to our panel of Surfing Magazine editors, Jeffrey's Bay offers long, fast barrels off an intense point break. The bay is divided into sections, so there are plenty of choices -- Kitchen Windows, Magna Tubes, Boneyards and, gnarliest of all, Supertubes. Expert surfers flock here for rides up to 300 meters long.",
            "latitude": "-33.961622774069966",
            "longitude":"25.12340553880252",
        },

	    {
            "id": 43,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Teahupo'o, Tahiti, French Polynesia",
            "photo": "https://www.singlequiver.com/enelpico/wp-content/uploads/2019/09/pato-teixera-surf-teahupoo.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Teahupo is one of the most perfect and feared waves in the world, says Paul about this unique Tahiti reef break. It is a short, intense ride and when it gets above 10 feet it is one of the most surreal waves in the world -- almost cartoonish. The heavy hollow-breaking wave is as dangerous as it is rewarding -- the name means Wall of Heads. The worlds biggest waves",
            "latitude": "-17.847637036510456",
            "longitude":"-149.2641860666429",
        },

	    {
            "id": 44,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Uluwatu and Kuta, Bali, Indonesia",
            "photo": "https://world-travel-guy-inboundhorizonsi.netdna-ssl.com/wp-content/uploads/2021/02/DJI_0377_1300.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "This paradise island attracts expert surfers from Australia and Hawaii, plus beginners from across the globe -- all can enjoy these perfect glassy faces.",
            "latitude": "-8.760598372877785",
            "longitude":"115.16929023300061",
        },

	    {
            "id": 45,
            "sport_id": 1,  
            "account_id": 1,
            "name": "P-Pass, Pohnpei, Federated States of Micronesia",
            "photo": "https://www.leeabbamonte.com/wp-content/uploads/2013/03/IMG_0793.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "P-Pass (short for Paliker Pass) is known for its incredible right-hander. It's just flawless, blue, reef-pass tubes, says Paul. Due to a remote location and the relatively high cost to reach it, the spot remains largely uncrowded despite its superlative rides.",
            "latitude": "6.941223349664511",
            "longitude":"158.16908578618626",
        },

	    {
            "id": 46,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Maverick's, California",
            "photo": "https://www.californiabeaches.com/wp-content/uploads/2014/09/IMG_5630-Large-1000x667.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "The wave of legends is surfed by only the gutsiest of board riders. The mammoth peak forms as a result of hair-raising storms out at sea and reaches bone-chilling heights of 25 meters. The only way to reach this wave is by boat or jet-ski; come at it at the wrong angle and you're fish food. In 1994, skilled Hawaiian big-wave surfer Mark Foo died surfing this point. Those surfers who do conquer its peak join a small club of overachievers.",
            "latitude": "37.496045412233514",
            "longitude":"-122.49638662214034",
        },
	
	    {
            "id": 47,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Hossegor, France",
            "photo": "https://www.alba-car.es/wp-content/uploads/2020/11/surf-hossegor2.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "This Atlantic surfing spot has been dubbed the surfing capital of Europe. The rich and famous have mansions and holiday homes near the beach -- previous owners include the likes of surfing songwriter Jack Johnson. People come from miles around to watch the pros ride tubes, which can rival Hawaii for heavy walls breaking on an unnervingly shallow sandbank. World's most hated airports",
            "latitude": "43.668622305341216",
            "longitude":"-1.4418781281282909",
        },
	
	    {
            "id": 48,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Puerto Escondido, Southern Oaxaca, Mexico",
            "photo": "http://cdn.cnn.com/cnnnext/dam/assets/180427150310-04-puerto-escondido.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "With a long, blessed surf season from March to December, this Mexican state attracts surfers with its powerful barrels and surrounding sandy point breaks. It's the main attraction when surfers head south of the border, says Paul, who recommends basing out of Puerto Escondido and driving to various points along the coast.",
            "latitude": "15.85733159544907",
            "longitude":"-97.07072715789863",
        },
	
	    {
            "id": 49,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Cloud Nine, Siargao Island, Philippines",
            "photo": "https://www.thecoastalcampaign.com/wp-content/uploads/2019/09/Cloud-9-Siargao-.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "This dramatic and powerful reef break, which crashes onto shallow razor-sharp coral, offers right and left death rides. Fearless surfers will experience a slice of paradise or hallucinations as waves wrap over them like a liquid cocoon. Skin and sometimes bone are often ripped to shreds by the ocean bed.",
            "latitude": "9.813784241435945",
            "longitude":"126.16515839626261",
        },
	
	    {
            "id": 50,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Lance's Right, Sipora, Mentawais Islands, Sumatera Barat, Indonesia",
            "photo": "https://mylemonmagazine.com/wp-content/uploads/2020/04/shutterstock_1119145235.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Near a seaside village on the tiny, beautiful Indonesian island of Sipora is a killer right tube that's worth the time, money and effort it takes to find it. Warm water, mechanically consistent waves, a cove lined with palm trees and dozens more world-class waves nearby -- no wonder the place is called perfection by avid surfers.",
            "latitude": "-2.029968636924638",
            "longitude":"99.61374053545296",
        },
	
	    {
            "id": 51,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Sultans, North Male, Maldives",
            "photo": "https://1.bp.blogspot.com/-lFU_funiLwk/X7JPL_LqURI/AAAAAAAB4-4/lnN5sUvEZuQr7PS6lqu8qNg3EYJDeDupwCLcBGAsYHQ/w1200-h630-p-k-no-nu/sultans-Thanburudhoo.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "A consistent reef wave that's absolutely pumping in the spring, the rocks at Sultans can be hazardous, so going with a live-aboard outfit such as Surf Atoll is recommended. The expert wave spotters can also deliver surfers to other fine points among the Maldives' 1,190 coral islands.",
            "latitude": "4.313748075076736",
            "longitude":"73.58527442666102",
        },

	    {
            "id": 52,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Trestles, Orange County, California",
            "photo": "https://www.surfholidays.com/assets/images/blog/2015-09-08-Trestles.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "The combination of easy paddle-outs and consistent high-quality breaks make the Trestles one of the most revered destinations in Southern California. Five spots make up the Trestles and provide a variety of left- and right-handed barrels -- the best surf (and the biggest crowds) are found at Lower Trestles. There's no other wave in the world that allows for such high performance surfing, and the fact that the A-frame is located in Orange County -- the heart of the surf industry -- makes it the epicenter for progressive aerials and surfing, says Surfing Magazine editor in chef Taylor Paul.",
            "latitude": "33.3860950336454",
            "longitude":"-117.59393593081279",
        },

	    {
            "id": 53,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Honolua Bay, Maui, Hawaii",
            "photo": "https://cdn.pixabay.com/photo/2019/10/20/16/57/maui-4564227_1280.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Finding this right-hand point break is tricky. Locals may respond to requests for directions with go back home, but this is a world-class ride with the added bonus of whale spotting from your board.",
            "latitude": "21.0139971826506",
            "longitude":"-156.6384996046076",
        },

	    {
            "id": 54,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Montanita Beach, Montanita, Ecuador",
            "photo": "https://beachlifeecuador.com/wp-content/uploads/2021/06/Playa-Montanita-Ecuador.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Not many travelers make it to (or even know about) this spot on the west coast of Ecuador. The majority head straight to the Galapagos Islands and miss this hidden spot, which wasn't even on the map a few years ago. There are only a thousand or so locals in Montanita and they are among the friendliest bunch of surfers you'll find. After pounding right-hand breaks, you can get to know them during apres-surf events on the village's bar strip.",
            "latitude": "-1.8201046297378098",
            "longitude":"-80.75754935741153",
        },

	    {
            "id": 55,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Rincon, Santa Barbara, California",
            "photo": "https://pbs.twimg.com/media/CjVpxfZUgAA5K2u.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "While it doesn't break often, when the surf is up, Rincon is the best point break in California, offering long, steep, right-hand waves on most big northwest swells. When that happens, this world famous spot gets extremely crowded.",
            "latitude": "34.3735591798938",
            "longitude":"-119.47764553741152",
        },

	    {
            "id": 56,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Nihiwatu, Sumba, Indonesia",
            "photo": "https://cf.bstatic.com/xdata/images/hotel/max1280x900/211621769.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "A private beach may grate on the idyllic surf attitude, but there's no denying the appeal of a break reserved just for you and a few others. All day, any day. Especially when it's frequently rated as one of the top 10 left-handers in the world, and has a stunning location.",
            "latitude": "-9.771735502064123",
            "longitude":"119.3681153286376",
        },
	
	    {
            "id": 57,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Manu Bay, Raglan, New Zealand",
            "photo": "https://surfsimply.com/wp-content/uploads/2016/05/Surf_Simply_Departure_Gate_Raglan_New_Zealand_feature-1.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Made famous in the 1960s as a location in the surf classic, The Endless Summer, atmosphere is key at this sleepy town. Bars and cafes play surf videos and serve healthy smoothies and fresh cakes. The waves on this wide-open bay range from one meter to about three, with an occasional barrel.",
            "latitude": "-37.82147628022414",
            "longitude":"174.8124895137614",
        },
	
	    {
            "id": 58,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Riyuewan, Sanya, Hainan Island, China",
            "photo": "https://d14fqx6aetz9ka.cloudfront.net/wp-content/uploads/2019/09/24105952/image0042.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "China isn't known for its beaches, let alone its surfing, but Hainan Island offers untouched tropical beaches with consistent uncrowded waves. Local outfit Surfing Hainan arranges transportation to beginner spots, such as Riyuewan Bay, and lesser known locations.",
            "latitude": "18.627133656709315",
            "longitude":"110.21781543835782",
        },
	
	    {
            "id": 59,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Jaws, Maui, Hawaii",
            "photo": "https://wpcdn.us-east-1.vip.tn-cloud.net/www.hawaiimagazine.com/content/uploads/2020/12/MikeCoots_Peahi_HawaiiMag-6882.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "The most iconic big wave reef break on the Hawaiian Islands takes its name from the ferocity of its legendary waves. It's a right and a left, and both offer giant barrels -- and potentially deadly consequences -- for anyone who's crazy enough to ride them, says Paul. Waves can reach an unbelievable 27 meters in winter, when strong winds create the monster swells for which the break is famed. In 2012, big wave legend Shane Dorian caught the extreme barrel ride that won Billabong's XXL Ride of the Year, the accomplishment that's finally getting him inducted into the Surfer's Hall of Fame this July.",
            "latitude": "20.943058702329818",
            "longitude":"-156.2968747182953",
        },
	
	    {
            "id": 60,
            "sport_id": 1,  
            "account_id": 1,
            "name": "The Box, Margaret River Valley, Australia",
            "photo": "https://summerstar.com.au/storage/app/media/blogs/margaret-river-surf-spots/the-box-margaret-river.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "The Box is possibly the world's most venerable slab wave, meaning that it transitions quickly from deep to shallow water. Named for its square barrel shape, the Box is said to be responsible for a resurgence among thrill seekers to search out dangerous slab waves around the world. It's sharky as all hell, but worth it, says Surfing Magazine editor in chief Taylor Paul. It has an incredibly late takeoff and offers a short, powerful right-hand barrel.",
            "latitude": "34.04089638096168",
            "longitude":"-118.53731516938889",
        },
	
	    {
            "id": 61,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Surfrider Beach, Malibu, California",
            "photo": "https://www.californiabeaches.com/wp-content/uploads/2014/09/bigstock-Malibu-Lagoon-State-Beach-in-M-459615401-e1486591810993-1000x615.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "These small, perfectly formed crests where Johnny Fain and Miki Dora surfed in the 1950s are a great place to grab a longboard and surf Beach Boys-style. Unfortunately, the place is absolutely rammed for exactly this reason.",
            "latitude": "34.033448051830895",
            "longitude":"-118.67927716777494",
        },

        {
            "id": 62,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Superbank, Gold Coast, Australia",
            "photo": "https://d14fqx6aetz9ka.cloudfront.net/wp-content/uploads/2019/03/30054440/E0I8196-1560x1024.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Superbank produces tubes and solid walls. It's crucial to save some energy for the two-kilometer walk along the beach back to where cars can be parked.",
            "latitude": "-28.163082200034882",
            "longitude":"153.54883274236894",
        },

	    {
            "id": 63,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Cloudbreak, Tavarua Island, Fiji",
            "photo": "https://isaworlds.com/sup/2016/wp-content/uploads/2016/11/RestaurantsAerial.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "In the easygoing South Pacific, Cloudbreak is strictly for experts. This brutal, hollow wave forms about 1,600 meters off the coast, and holds for up to 500 meters, reaching 10 meters in size.",
            "latitude": "-17.85795720246943",
            "longitude":"177.2018373095503",
        },

	    {
            "id": 64,
            "sport_id": 1,  
            "account_id": 1,
            "name": " Watergate Bay, Cornwall, England",
            "photo": "https://watergatebay.azurewebsites.net/media/2500/watergate-bay-hotel-cornwall.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Watergate Bay isn't as famous as Fistral Bay, but it has more English charm, is less crowded and is equally as surfable, with waves ranging from 30 centimeters to three meters.",
            "latitude": "50.44080960412142",
            "longitude":"-5.041300457353162",
        },

	    {
            "id": 65,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Backdoor, Oahu, Hawaii",
            "photo": "https://ep00.epimg.net/elpais/imagenes/2013/06/04/album/1370334695_972119_1370335652_album_normal.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "An experts-only spot, the reef bottom here creates potent, hollow, fast and intimidating world-class tubes. Epic, though not quite as epic as its North Shore neighbor, Pipeline. Non-expert surfers should probably just experience this break from the beach.",
            "latitude": "21.712893692747276",
            "longitude":"-157.9947628325152",
        },

	    {
            "id": 66,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Pasta Point, Maldives",
            "photo": "https://soulridercamp.com/83/pasta-point-resort-pack/ajax/crop.php?w=800&h=600&src=scPa1G4n.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "One of the most famous waves in the Maldives, this break offers left-hand rides and 100 meters of pure tube riding out to sea. There's a catch: only Dhonveli Beach Resort & Spa guests can access the spot. A stay on the exclusive island costs upwards of $340 per night.",
            "latitude": "4.318088059672672",
            "longitude":"73.59182955734975",
        },

	    {
            "id": 67,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Tamarindo Beach, Tamarindo, Costa Rica",
            "photo": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Costa_Rica_Playa_Tamarindo_and_Rivermouth_2007_Aerial_Photograph_Tamarindowiki_01.JPG", 
            "level": "Begginers",
            "description": "Good for beginners and experts, this half-kilometer stretch of beach with warm water generates waves that reach heights of three meters. Howler monkeys swing through the trees and parakeets screech in the background.",
            "latitude": "10.302745974969621",
            "longitude":"-85.84098818876741",
        },
	
	    {
            "id": 68,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Bundoran Beach, County Donegal, Ireland",
            "photo": "https://i.pinimg.com/originals/1e/bf/5a/1ebf5a861dd49f8cbb8dda410a59d89c.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "These shimmering green waters produce rolling waves, which are shaped by the headlands and flat rock reefs. The cold water doesn't deter die-hards. Locals will offer tips and advice to visiting surfers.",
            "latitude": "54.483257936798644",
            "longitude":"-8.277982614912471",
        },
	
	    {
            "id": 69,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Rincon, Puerto Rico",
            "photo": "https://revistaturismoyviajes.com/wp-content/uploads/2018/11/Rincon-Puerto-Rico-4-1024x576.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Not to be confused with Rincon, California (also on this list), this once sleepy Puerto Rican town on the Caribbean Sea has become famous for surfing. The green hill is a great place from which to scout the best surf.",
            "latitude": "18.35119346033809",
            "longitude":"-67.26375837638231",
        },
	
	    {
            "id": 70,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Hanalei Bay, Hawaii",
            "photo": "https://www.hawaiimagazine.com/content/uploads/2021/05/s/r/gettyimages-1000512980.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Set in a sandy, horseshoe bay, Hanalei on Kauai is particularly pretty, with waterfalls tumbling down magnificent tropical cliffs in the background. Pros love it for its overhead tubes and consistently fine waves. Others just love the super-chill vibe of a perfect beach town.",
            "latitude": "22.20340808473571",
            "longitude":"-159.5045345453531",
        },
	
	    {
            "id": 71,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Carrapateira, Portugal",
            "photo": "https://www.shamaretreats.com/wp-content/uploads/2021/05/c61cfd74-f7bc-41fb-a514-2ddd55d0d301-istock-bordeira-1.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "This lovely left-hand Euro break with plenty of shelter from the rocks can reach up to three meters during mid-high tide. Best of all, it's usually empty.",
            "latitude": "37.19803305637659",
            "longitude":"-8.903036803389327",
        },
	
	    {
            "id": 72,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Coconuts, Samoa",
            "photo": "https://media01.stockfood.com/largepreviews/MjE3MDQ5MTcyMg==/70015862-Coconut-Trees-and-Blowholes-Taga-Savai-i-Samoa.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Even professional surfers come close to cracking their boards at this classic wave, which breaks over live coral and on top days offers 150-meter rides.",
            "latitude": "-14.008260594885982",
            "longitude":"-171.79179615972373",
        },

	    {
            "id": 73,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Sao Francisco do Sul, Brazil",
            "photo": "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/119314913.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Surfing competitions are often held at this decent quality sandbar below San Paulo on the east coast of Brazil. There's a fun-loving atmosphere, plus some nice bars from which to watch the surf until sunset and eat tasty local grub.",
            "latitude": "-26.225488673164392",
            "longitude":"-48.5118564551455",
        },

	    {
            "id": 74,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Pedra Branca Ericeira, Portugal",
            "photo": "https://rutas-turisticas.com/imagens/destinos/pt/large/IMGD3-840-13776-pedra_branca_ericeira_surf_spot.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Along this sublime surf beach 48 kilometers north of Lisbon on the Atlantic coast you'll find a sleepy fishing-village-turned-surfer town with six kilometers of stunning beach, including the sandbar Sao Lorenzo and the epic Pedra Branca reef break. It's one of the best waves in Europe.New Zealands best beaches",
            "latitude": "38.978271106485636",
            "longitude":"-9.421391408783094",
        },

	    {
            "id": 75,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Les Cavaliers, Anglet, France",
            "photo": "https://cdt64.media.tourinsoft.eu/upload/spot-la-madrague-1.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Flanked by two rocky girders, surfers should use the channel at the right-hand side to paddle into this killer wave, which works perfectly in offshore winds with west swells. Locals can be aggressive when they feel their waves have been stolen.",
            "latitude": "43.52098219650514",
            "longitude":"-1.5265500269460774",
        },

	    {
            "id": 76,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Killer Point, Taghazoute, Morocco",
            "photo": "https://surfberbere.com/wp-content/uploads/2016/03/la_source_and_the_view_up_to_killers.png", 
            "level": "–Level: Advanced - experienced",
            "description": "Popularized by hippies in the 1960s, this southern Moroccan village makes for an utterly unique surf trip. A perfectly peeling wave breaks over a cliff shelf, which was named after the many killer whales in the area.",
            "latitude": "30.54492794173471",
            "longitude":"-9.711763290328971",
        },

	    {
            "id": 77,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Byron Bay, New South Wales, Australia",
            "photo": "https://www.worldbeachguide.com/photos/byron-bay-beach.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Popular among European backpackers, this mellow town is home to bars that religiously play reggae and waves along a 70-kilometer stretch of sand. Shark nets have been implemented, but look out for the sunken ship.",
            "latitude": "-28.640016358697665",
            "longitude":"153.6171086353325",
        },
	
	    {
            "id": 78,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Tofino, Vancouver Island, Canada",
            "photo": "http://cdn.cnn.com/cnnnext/dam/assets/200928112745-10-tofino-crunchy-city-canada-restricted.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "The surfing capital of Canada offers a picturesque break on the west coast of the island. Unique feature: it's surrounded by a looming rainforest. Suitable for all abilities, the only prerequisite is a thick wetsuit -- it gets cold out there.",
            "latitude": "49.10223741691015",
            "longitude":"-125.87446876703413",
        },
	
	    {
            "id": 79,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Ponta Preta, Maio, Cape Verde",
            "photo": "https://i.pinimg.com/736x/f9/05/97/f90597c7bf996961a377e0cda9a776c3--capes.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "In Portuguese Ponta Preta means black point, and if this was a ski slope it would most definitely be a black run. This break over exposed reef offers thrilling rides in winter for expert surfers.",
            "latitude": "15.12911767547476",
            "longitude":"-23.20691003442169",
        },
	
	    {
            "id": 80,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Biarritz, France",
            "photo": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Biarritz-Plage.JPG", 
            "level": "–Level: Advanced - experienced",
            "description": "Surfers have been hitting this spot since the 1950s. It pumps all year around thanks to ferocious North Atlantic swells that make their way down the Gulf de Gascogne.",
            "latitude": "43.48771201855646",
            "longitude":"-1.5558763904856603",
        },
	
	    {
            "id": 81,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Surf pool, United Arab Emirates",
            "photo": "https://totalsurfcamp.com/sites/default/files/surfcamps/%5Btitle-raw%5D/wadi-adventure.jpg", 
            "level": "All levels",
            "description": "The only artificial surf site to make the list, the wave pool at Wadi Adventure in the United Arab Emirates has converted its share of skeptics, inspiring some to proclaim it the future of surfing. The surf pool can be adjusted to create rights, lefts and even barrels. It may not be the best wave in the world, but it's the best wave pool in the world, says Surfing Magazine editor in chief Taylor Paul.",
            "latitude": "25.010396260212435",
            "longitude":"55.02729180600895",
        },
	
	    {
            "id": 82,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Cape Hatteras Lighthouse, Buxton, North Carolina",
            "photo": "https://ewscripps.brightspotcdn.com/dims4/default/a1aa0fe/2147483647/strip/true/crop/2000x1125+0+48/resize/1280x720!/quality/90/?url=http%3A%2F%2Fewscripps-brightspot.s3.amazonaws.com%2F9a%2Fd3%2F4f304b1247388c0dff7adda7170a%2Fap-18254602046735.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Cape Hatteras Lighthouse has been popular since the 1970s and renowned for good surf caused by deadly hurricanes, which have over the years caused numerous shipwrecks and given it the nickname the Atlantic graveyard.",
            "latitude": "35.25019541359969",
            "longitude":"-75.52311747642442",
        },

        {
            "id": 83,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Black's Beach, San Diego, California",
            "photo": "https://viewfinder.expedia.com/wp-content/uploads/2019/08/blacks-beach-header-1140x630.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "One for seasoned professionals, Black's Beach is one of the most powerful breaks in California. San Diego's best surfers flock here; it can get crowded on weekends.",
            "latitude": "32.89175761521377",
            "longitude":"-117.25426611147603",
        },

        {
            "id": 84,
            "sport_id": 1,  
            "account_id": 1,
            "name": "The Bubble, Fuerteventura, Canary Islands",
            "photo": "https://thesurfatlas.com/wp-content/uploads/2020/02/Fuerteventura-surf.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "On the north shore off the coast of El Jablito, this expert right-hand tube works best when it's head-high to double overhead. Similar to many of the waves in the Canaries, the only thing that hurts this reef break are aggressive locals who resent giving visiting surfers a turn on their wave. Visitors may find themselves in a paddling race to get a shot at riding this classic face.",
            "latitude": "28.71618474968251",
            "longitude":"-13.98495692269392",
        },

        {
            "id": 85,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Surfer's Point, Barbados",
            "photo": "https://i.ytimg.com/vi/doJN8Wu-8TU/maxresdefault.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "On the southernmost tip of Barbados you'll find hollow and fast beginner-to-intermediate peaks scattered along the bay. Waves face both left and right.",
            "latitude": "13.052027359371612",
            "longitude":"-59.504833245529376",
        },
        {
            "id": 86,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Arugam Bay, Sri Lanka",
            "photo": "https://1001beach.com/img/posts/2122/1200/arugam_bay-1.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Not just a great surf spot with a right-hand peak, surfers here share the beach with wild monkeys and elephants that graze in the forest nearby.",
            "latitude": "6.84104962039174",
            "longitude":"81.83670221852435",
        },

        {
            "id": 87,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Surin Beach, Phuket, Thailand",
            "photo": "https://a.cdn-hotels.com/gdcs/production33/d1061/2de45452-8f22-47e0-ae85-39b070b6dfb4.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Though Thailand isn't a world-class spot, we like the location, the warm opaque waters, fresh pad Thai at street stalls and raucous nightlife.",
            "latitude": "7.974778438085937",
            "longitude":"98.27849312825417",
        },

        {
            "id": 88,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Fulong Beach, Taiwan",
            "photo": "https://m.justgola.com/media/a/00/0c/53064_og_1.jpeg", 
            "level": "–Level: Advanced - experienced",
            "description": "In northeast Taiwan, Fulong Beach has great camping nearby and produces thrilling right- and left-peeling waves from a sandbar. Waves range from one to two meters.",
            "latitude": "25.021497307503875",
            "longitude":"121.94462226376672",
        },

        {
            "id": 89,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Baja Malibu, Baja Norte, Mexico",
            "photo": "https://www.surf-forecast.com/system/images/10872/large/Baja-Malibu.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "Though water cleanliness is an issue (don't swallow any), this exposed break works when offshore winds blow in from the east. You can ride both right and left and fall onto a sandy base.",
            "latitude": "32.41706382701176",
            "longitude":"-117.09649596419837",
        },

        {
            "id": 90,
            "sport_id": 1,  
            "account_id": 1,
            "name": "Eisbach, Munich",
            "photo": "https://previews.123rf.com/images/gameover/gameover1703/gameover170300036/73736098-munich-surfer-sur-la-vague-artificielle-sur-la-eisbach-petite-rivi%C3%A8re-%C3%A0-travers-le-englischer-garten.jpg", 
            "level": "–Level: Advanced - experienced",
            "description": "The most unusual wave on the list is found on an artificial river next to Englischer Garten, Munich's main park. It's completely landlocked. This one meter standing wave (meaning you don't move along the river, but surf in the same spot) is created by water pumped fast against a large rock, forming a crest. As long as there's enough water the ride never stops ... until you fall.",
            "latitude": "48.16074315475986",
            "longitude":"11.605522443242311",
        }
    ],
}